fail_fast: true
repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: uv run --no-sync black docling_core test
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: uv run --no-sync isort docling_core test
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: uv run --no-sync autoflake docling_core test
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        entry: uv run --no-sync mypy docling_core test
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        entry: uv run --no-sync flake8 docling_core
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: pytest
        name: Pytest
        entry: uv run --no-sync pytest --cov=docling_core --cov-report=xml test
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: docs
        name: Docs
        entry: uv run --no-sync python -m docling_core.utils.generate_docs docs
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.8
    hooks:
      - id: uv-lock
