fail_fast: true
repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: uv run --no-sync black docling_ibm_models
        pass_filenames: false
        language: system
        files: '\.py$'
      - id: isort
        name: isort
        entry: uv run --no-sync isort docling_ibm_models
        pass_filenames: false
        language: system
        files: '\.py$'
      - id: system
        name: MyPy
        entry: uv run --no-sync mypy docling_ibm_models
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.8
    hooks:
      - id: uv-lock
